name: sip_phone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # SIP UA package for VoIP functionality
  sip_ua: ^1.0.1
  # Additional dependencies for VoIP functionality
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.5.1
  
  # Data storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Contacts and phone functionality  
  device_info_plus: ^9.1.2
  flutter_contacts: ^1.1.9
  
  # Modern UI and animations
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  
  # Audio
  audioplayers: ^5.2.1
  
  # URL launcher for phone calls
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
